### ISSUE TITLE
add description to avoid confusion about this being an official replicant repo

### ISSUE THREAD

**Issue by herbsmn** [Midas-Mainline/android_device_midas_common#1]
Hello! Is there any chance you could add something in the descriptions of the repos in https://github.com/ReplicantOS-midas so as to avoid people thinking that this is an official Replicant github repo? For instance, could you put "ChronoMonochrome fork of Replicant" or something like that in the repo descriptions? Thanks!

**Comment by ChronoMonochrome** [comment]
Hey!

Sorry for the confusion that was created by these repos. 
This organization is now available as https://github.com/Midas-Mainline .

**Comment by herbsmn** [comment]
No hard feelings! :-) Thanks for making the change!
